<?php
// languages en
$languages = [
    'mahjoob' => 'Mahjoob',
    'title' => 'Mahjoob' . ($hostname ? ' - ' . $hostname : ''),
    'home' => 'Home',
    'settings' => 'Settings',
    'logout' => 'Logout',
    'welcome' => 'Welcome to Pi-hole',
    'description' => 'Network-wide ad blocking via your own hardware.',
    'status' => 'Status',
    'active' => 'Active',
    'blocking_disabled' => 'Blocking disabled',
    'dns_not_running' => 'DNS service not running',
    'unknown' => 'Unknown',
    'load' => 'Load',
    'memory_usage' => 'Memory usage',
    'temperature' => 'Temp',
    'main' => 'Main',
    'dashboard' => 'Dashboard',
    'analysis' => 'Analysis',
    'query_log' => 'Query Log',
    'long_term_data' => 'Long-term Data',
    'graphics' => 'Graphics',
    'top_lists' => 'Top Lists',
    'group_management' => 'Group Management',
    'groups' => 'Groups',
    'clients' => 'Clients',
    'domains' => 'Domains',
    'adlists' => 'Adlists',
    'dns_control' => 'DNS Control',
    'disable_blocking' => 'Disable Blocking',
    'indefinitely' => 'Indefinitely',
    'for_10_seconds' => 'For 10 seconds',
    'for_30_seconds' => 'For 30 seconds',
    'for_5_minutes' => 'For 5 minutes',
    'custom_time' => 'Custom time',
    'enable_blocking' => 'Enable Blocking',
    'local_dns' => 'Local DNS',
    'dns_records' => 'DNS Records',
    'cname_records' => 'CNAME Records',
    'system' => 'System',
    'tools' => 'Tools',
    'pihole_diagnosis' => 'Pi-hole diagnosis',
    'update_gravity' => 'Update Gravity',
    'search_adlists' => 'Search Adlists',
    'audit_log' => 'Audit log',
    'tail_pihole_log' => 'Tail pihole.log',
    'tail_ftl_log' => 'Tail FTL.log',
    'generate_debug_log' => 'Generate debug log',
    'network' => 'Network',
    'donate' => 'Donate',
    'only_a_aaaa_queries' => 'only A + AAAA queries',
    'total_queries' => 'Total queries',
    'active_clients' => 'active clients',
    'queries_blocked' => 'Queries Blocked',
    'list_blocked_queries' => 'List blocked queries',
    'percentage_blocked' => 'Percentage Blocked',
    'list_all_queries' => 'List all queries',
    'domains_on_adlists' => 'Domains on Adlists',
    'manage_adlists' => 'Manage adlists',
    'total_queries_last_hours' => 'Total queries over last <span class="maxlogage-interval">24</span> hours',
    'client_activity_last_hours' => 'Client activity over last <span class="maxlogage-interval">24</span> hours',
    'query_types' => 'Query Types',
    'upstream_servers' => 'Upstream servers',
    'top_permitted_domains' => 'Top Permitted Domains',
    'domain' => 'Domain',
    'hits' => 'Hits',
    'frequency' => 'Frequency',
    'top_blocked_domains' => 'Top Blocked Domains',
    'top_clients_total' => 'Top Clients (total)',
    'top_clients_blocked_only' => 'Top Clients (blocked only)',
    'client' => 'Client',
    'requests' => 'Requests',
    'showing' => 'showing',
    'showing_permitted' => 'showing permitted',
    'showing_blocked' => 'showing blocked',
    'showing_no_queries_due_to_setting' => 'showing no queries (due to setting)',
    'showing_blocked_queries_for_client' => 'showing blocked queries for client ',
    'show_all' => 'show all',
    'showing_all_queries_within_pihole_log' => 'showing all queries within the Pi-hole log',
    'queries_blocked_by_pihole' => 'queries blocked by Pi-hole',
    'queries_answered_from_cache' => 'queries answered from cache',
    'queries_for_upstream_destination' => 'queries for upstream destination ',
    'type_queries' => 'type ',
    'queries' => ' queries',
    'queries_for_domain' => 'queries for domain ',
    'queries_within_specified_time_interval' => 'queries within specified time interval',
    'up_to_100_queries' => 'up to 100 queries',
    'close' => 'Close',
    'adding_domain_to_list' => 'Adding ',
    'to_the' => ' to the ',
    'domain_successfully_added_to_list' => ' successfully added to the ',
    'timeout_or_network_error' => 'Timeout or Network Connection Error!',
    'recent_queries' => 'Recent Queries ',
    'time' => 'Time',
    'type' => 'Type',
    'domain' => 'Domain',
    'client' => 'Client',
    'status' => 'Status',
    'reply' => 'Reply',
    'action' => 'Action',
    'note_queries_pi_hole_hostname_never_logged' => 'Note: Queries for <code>pi.hole</code> and the hostname are never logged.',
    'filtering_options' => 'Filtering options:',
    'click_value_add_remove_filter' => 'Click a value in a column to add/remove that value to/from the filter',
    'hold_down_keys_computer' => 'On a computer: Hold down <kbd>Ctrl</kbd>, <kbd>Alt</kbd>, or <kbd>&#8984;</kbd> to allow highlighting for copying to clipboard',
    'long_press_mobile' => 'On a mobile: Long press to highlight the text and enable copying to clipboard',
    'clear_filters' => 'Clear filters',
    'compute_graphical_statistics' => 'Compute graphical statistics from the Pi-hole query database',
    'select_date_time_range' => 'Select date and time range',
    'click_to_select_date_time_range' => 'Click to select date and time range',
    'timeout_warning_message' => 'Depending on how large of a range you specified, the request may time out while Pi-hole tries to retrieve all the data.',
    'queries_over_selected_time_period' => 'Queries over the selected time period',
    'page_header_specify_date_range' => 'Specify date range to be queried from the Pi-hole query database',
    'box_title_select_date_time_range' => 'Select date and time range',
    'alert_new_options_selected' => 'New options selected. Please reload the data or choose another time range.',
    'button_reload_data' => 'Reload Data',
    'click_to_select_date_time_range' => 'Click to select date and time range',
    'label_query_status' => 'Query status:',
    'checkbox_permitted_forwarded' => 'Permitted: forwarded',
    'checkbox_permitted_cached' => 'Permitted: cached',
    'checkbox_permitted_stale_cache' => 'Permitted: stale cache',
    'checkbox_permitted_retried' => 'Permitted: retried',
    'checkbox_blocked_gravity' => 'Blocked: gravity',
    'checkbox_blocked_external' => 'Blocked: external',
    'checkbox_blocked_dbbusy' => 'Blocked: database busy',
    'checkbox_blocked_exact_blacklist' => 'Blocked: exact blacklist',
    'checkbox_blocked_regex_blacklist' => 'Blocked: regex blacklist',
    'checkbox_blocked_special_domain' => 'Blocked: special domain',
    'checkbox_blocked_gravity_cname' => 'Blocked: gravity (CNAME)',
    'checkbox_blocked_exact_blacklist_cname' => 'Blocked: exact blacklist (CNAME)',
    'checkbox_blocked_regex_blacklist_cname' => 'Blocked: regex blacklist (CNAME)',
    'timeout_warning_message' => 'Depending on how large of a range you specified, the request may time out while Pi-hole tries to retrieve all the data.',
    'total_queries' => 'Total Queries',
    'queries_blocked' => 'Queries Blocked',
    'queries_blocked_wildcards' => 'Queries Blocked (Wildcards)',
    'percentage_blocked' => 'Percentage Blocked',
    'recent_queries' => 'Recent Queries',
    'time' => 'Time',
    'type' => 'Type',
    'domain' => 'Domain',
    'client' => 'Client',
    'status' => 'Status',
    'reply' => 'Reply',
    'action' => 'Action',
    'button_close' => 'Close',
    'compute_top_lists' => 'Compute Top Lists from the Pi-hole query database',
    'select_date_time_range' => 'Select date and time range',
    'alert_new_options_selected' => 'New options selected. Please reload the data or choose another time range.',
    'button_reload_data' => 'Reload Data',
    'click_to_select_date_time_range' => 'Click to select date and time range',
    'label_query_status' => 'Query status:',
    'checkbox_permitted_forwarded' => 'Permitted: forwarded',
    'checkbox_permitted_cached' => 'Permitted: cached',
    'checkbox_permitted_stale_cache' => 'Permitted: stale cache',
    'checkbox_permitted_retried' => 'Permitted: retried',
    'checkbox_blocked_gravity' => 'Blocked: gravity',
    'checkbox_blocked_external' => 'Blocked: external',
    'checkbox_blocked_dbbusy' => 'Blocked: database busy',
    'checkbox_blocked_exact_blacklist' => 'Blocked: exact blacklist',
    'checkbox_blocked_regex_blacklist' => 'Blocked: regex blacklist',
    'checkbox_blocked_special_domain' => 'Blocked: special domain',
    'checkbox_blocked_gravity_cname' => 'Blocked: gravity (CNAME)',
    'checkbox_blocked_exact_blacklist_cname' => 'Blocked: exact blacklist (CNAME)',
    'checkbox_blocked_regex_blacklist_cname' => 'Blocked: regex blacklist (CNAME)',
    'timeout_warning_message' => 'Depending on how large of a range you specified, the request may time out while Pi-hole tries to retrieve all the data.',
    'total_queries' => 'Total Queries',
    'queries_blocked' => 'Queries Blocked',
    'queries_blocked_wildcards' => 'Queries Blocked (Wildcards)',
    'percentage_blocked' => 'Percentage Blocked',
    'recent_queries' => 'Recent Queries',
    'time' => 'Time',
    'type' => 'Type',
    'domain' => 'Domain',
    'client' => 'Client',
    'status' => 'Status',
    'reply' => 'Reply',
    'action' => 'Action',
    'button_close' => 'Close',
    'button_reload_data' => 'Reload Data',
    'compute_top_lists' => 'Compute Top Lists from the Pi-hole query database',
    'top_domains' => 'Top Domains',
    'top_blocked_domains' => 'Top Blocked Domains',
    'top_clients' => 'Top Clients',
    'hits' => 'Hits',
    'frequency' => 'Frequency',
    'client' => 'Client',
    'requests' => 'Requests',
    'group_management' => 'Group management',
    'add_new_group' => 'Add a new group',
    'label_name' => 'Name:',
    'label_description' => 'Description:',
    'placeholder_group_name' => 'Group name or space-separated group names',
    'placeholder_group_description' => 'Group description (optional)',
    'hints' => 'Hints:',
    'hint_multiple_groups' => 'Multiple groups can be added by separating each group name with a space',
    'hint_group_names_in_quotes' => 'Group names can have spaces if entered in quotes. e.g "My New Group"',
    'button_add' => 'Add',
    'list_of_groups' => 'List of groups',
    'table_header_id' => 'ID',
    'table_header_name' => 'Name',
    'table_header_status' => 'Status',
    'table_header_description' => 'Description',
    'table_header_action' => 'Action',
    'button_reset_sorting' => 'Reset sorting',
    'top_domains' => 'Top Domains',
    'top_blocked_domains' => 'Top Blocked Domains',
    'top_clients' => 'Top Clients',
    'hits' => 'Hits',
    'frequency' => 'Frequency',
    'client' => 'Client',
    'requests' => 'Requests',
    'button_close' => 'Close',
    'group_management' => 'Group management',
    'client_group_management' => 'Client group management',
    'add_new_client' => 'Add a new client',
    'label_known_clients' => 'Known clients:',
    'label_comment' => 'Comment:',
    'placeholder_client_description' => 'Client description (optional)',
    'instruction_select_or_add_client' => 'You can select an existing client or add a custom one by typing into the field above and confirming your entry with <kbd>&#x23CE;</kbd>.',
    'instruction_client_description' => 'Clients may be described either by their IP addresses (IPv4 and IPv6 are supported),
    IP subnets (CIDR notation, like <code>192.168.2.0/24</code>),
    their MAC addresses (like <code>12:34:56:78:9A:BC</code>),
    by their hostnames (like <code>localhost</code>), or by the interface they are connected to (prefaced with a colon, like <code>:eth0</code>).
    Note that client recognition by IP addresses (incl. subnet ranges) are preferred over MAC address, host name or interface recognition as
    the two latter will only be available after some time.
    Furthermore, MAC address recognition only works for devices at most one networking hop away from your Pi-hole.',
    'instruction_client_recognition' => 'Note that client recognition by IP addresses (incl. subnet ranges) are preferred over MAC address, host name or interface recognition as
    the two latter will only be available after some time.
    Furthermore, MAC address recognition only works for devices at most one networking hop away from your Pi-hole.',
    'button_add' => 'Add',
    'list_of_configured_clients' => 'List of configured clients',
    'table_header_id' => 'ID',
    'table_header_empty' => '',
    'table_header_client' => 'Client',
    'table_header_client_tooltip' => 'Acceptable values are: IP address, subnet (CIDR notation), MAC address (AA:BB:CC:DD:EE:FF format) or host names.',
    'table_header_comment' => 'Comment',
    'table_header_group_assignment' => 'Group assignment',
    'table_header_action' => 'Action',
    'button_reset_sorting' => 'Reset sorting',
    'timeout_warning_message' => 'Depending on how large of a range you specified, the request may time out while Pi-hole tries to retrieve all the data.',
    'select_known_clients_loading' => 'Loading...',
    'domain_management' => 'Domain management',
    'add_new_domain_or_regex_filter' => 'Add a new domain or regex filter',
    'label_domain' => 'Domain:',
    'label_domain_comment' => 'Comment:',
    'placeholder_domain' => 'Domain to be added',
    'placeholder_domain_comment' => 'Description (optional)',
    'label_regex' => 'Regular Expression:',
    'label_regex_comment' => 'Comment:',
    'placeholder_regex' => 'RegEx to be added',
    'placeholder_regex_comment' => 'Description (optional)',
    'tab_domain' => 'Domain',
    'tab_regex_filter' => 'RegEx filter',
    'checkbox_add_wildcard' => 'Add domain as wildcard',
    'checkbox_label_add_wildcard' => '<strong>Add domain as wildcard</strong>',
    'checkbox_description_add_wildcard' => 'Check this box if you want to involve all subdomains. The entered domain will be converted to a RegEx filter while adding.',
    'note_auto_assignment' => '<strong>Note:</strong><br>
        The domain or regex filter will be automatically assigned to the Default Group.<br>
        Other groups can optionally be assigned in the list below (using <b>Group assignment</b>).',
    'button_add_to_blacklist' => 'Add to Blacklist',
    'button_add_to_whitelist' => 'Add to Whitelist',
    'list_of_domains' => 'List of domains',
    'table_header_id' => 'ID',
    'table_header_empty' => '',
    'table_header_domain_regex' => 'Domain/RegEx',
    'table_header_type' => 'Type',
    'table_header_status' => 'Status',
    'table_header_comment' => 'Comment',
    'table_header_group_assignment' => 'Group assignment',
    'table_header_action' => 'Action',
    'button_reset_sorting' => 'Reset sorting',
    'filter_exact_whitelist' => 'Exact whitelist',
    'filter_regex_whitelist' => 'Regex whitelist',
    'filter_exact_blacklist' => 'Exact blacklist',
    'filter_regex_blacklist' => 'Regex blacklist',
    'filter_types_label' => 'Filter Types:',
    'instruction_accept_values' => 'Acceptable values are: IP address, subnet (CIDR notation), MAC address (AA:BB:CC:DD:EE:FF format) or host names.',
    'instruction_help_regex' => 'Need help to write a proper RegEx rule? Have a look at our online
        <a href="https://docs.pi-hole.net/ftldns/regex/tutorial" rel="noopener" target="_blank">
            regular expressions tutorial</a>.',
    'button_add_to_blacklist' => 'Add to Blacklist',
    'button_add_to_whitelist' => 'Add to Whitelist',
    'button_reset_sorting' => 'Reset sorting',
    'adlist_group_management' => 'Adlist group management',
    'add_new_adlist' => 'Add a new adlist',
    'label_address' => 'Address:',
    'label_comment' => 'Comment:',
    'placeholder_address' => 'URL or space-separated URLs',
    'placeholder_adlist_comment' => 'Adlist description (optional)',
    'hints' => 'Hints:',
    'hint_run_pihole_g' => 'Please run <code>pihole -g</code> or update your gravity list <a href="gravity.php">online</a> after modifying your adlists.',
    'hint_multiple_adlists' => 'Multiple adlists can be added by separating each <i>unique</i> URL with a space',
    'hint_click_icon_info' => 'Click on the icon in the first column to get additional information about your lists. The icons correspond to the health of the list.',
    'button_add' => 'Add',
    'list_of_adlists' => 'List of adlists',
    'table_header_id' => 'ID',
    'table_header_empty' => '',
    'table_header_address' => 'Address',
    'table_header_status' => 'Status',
    'table_header_comment' => 'Comment',
    'table_header_group_assignment' => 'Group assignment',
    'table_header_action' => 'Action',
    'button_reset_sorting' => 'Reset sorting',
    'local_dns_records_title' => 'Local DNS Records [A/AAAA]',
    'local_dns_records_subtitle' => 'On this page, you can add domain/IP associations',
    'add_new_domain_ip_combination' => 'Add a new domain/IP combination',
    'label_domain' => 'Domain:',
    'label_ip_address' => 'IP Address:',
    'placeholder_domain_list' => 'Domain or comma-separated list of domains',
    'placeholder_ip_address' => 'Associated IP address',
    'note' => 'Note:',
    'note_dns_records_order' => 'The order of locally defined DNS records is:',
    'note_dns_records_item1' => "The device's host name and <code>pi.hole</code>",
    'note_dns_records_item2' => 'Configured in a config file in <code>/etc/dnsmasq.d/</code>',
    'note_dns_records_item3' => 'Read from <code>/etc/hosts</code>',
    'note_dns_records_item4' => 'Read from the "Local (custom) DNS" list (stored in <code>/etc/pihole/custom.list</code>)',
    'note_only_first_record' => 'Only the first record will trigger an address-to-name association.',
    'button_add' => 'Add',
    'button_clear_filters' => 'Clear Filters',
    'list_of_local_dns_domains' => 'List of local DNS domains',
    'table_header_domain' => 'Domain',
    'table_header_ip' => 'IP',
    'table_header_action' => 'Action',
    'button_add' => 'Add',
    'button_clear_filters' => 'Clear Filters',
    'local_cname_records_title' => 'Local CNAME Records',
    'local_cname_records_subtitle' => 'On this page, you can add CNAME records.',
    'add_new_cname_record' => 'Add a new CNAME record',
    'label_domain' => 'Domain:',
    'label_target_domain' => 'Target Domain:',
    'placeholder_domain_list' => 'Domain or comma-separated list of domains',
    'placeholder_target_domain' => 'Associated Target Domain',
    'note' => 'Note:',
    'note_cname_target_requirement' => 'The target of a <code>CNAME</code> must be a domain that the Pi-hole already has in its cache or is authoritative for. This is a universal limitation of <code>CNAME</code> records.',
    'note_cname_no_upstream_queries' => 'The reason for this is that Pi-hole will not send additional queries upstream when serving <code>CNAME</code> replies. As consequence, if you set a target that isn\'t already known, the reply to the client may be incomplete. Pi-hole just returns the information it knows at the time of the query. This results in certain limitations for <code>CNAME</code> targets, for instance, only <i>active</i> DHCP leases work as targets - mere DHCP <i>leases</i> aren\'t sufficient as they aren\'t (yet) valid DNS records.',
    'note_cname_external_domains' => 'Additionally, you can\'t <code>CNAME</code> external domains (<code>bing.com</code> to <code>google.com</code>) successfully as this could result in invalid SSL certificate errors when the target server does not serve content for the requested domain.',
    'button_add' => 'Add',
    'button_clear_filters' => 'Clear Filters',
    'list_of_local_cname_records' => 'List of local CNAME records',
    'table_header_domain' => 'Domain',
    'table_header_target' => 'Target',
    'table_header_action' => 'Action',
    'local_dns_records_title' => 'Local DNS Records [A/AAAA]',
    'local_dns_records_subtitle' => 'On this page, you can add domain/IP associations.',
    'add_new_dns_record' => 'Add a new domain/IP combination',
    'label_domain' => 'Domain:',
    'label_ip_address' => 'IP Address:',
    'placeholder_domain_list' => 'Domain or comma-separated list of domains',
    'placeholder_ip_address' => 'Associated IP address',
    'note' => 'Note:',
    'note_dns_records_order' => 'The order of locally defined DNS records is:',
    'note_dns_records_item1' => "The device's host name and <code>pi.hole</code>",
    'note_dns_records_item2' => 'Configured in a config file in <code>/etc/dnsmasq.d/</code>',
    'note_dns_records_item3' => 'Read from <code>/etc/hosts</code>',
    'note_dns_records_item4' => 'Read from the "Local (custom) DNS" list (stored in <code>/etc/pihole/custom.list</code>)',
    'note_only_first_record' => 'Only the first record will trigger an address-to-name association.',
    'button_add' => 'Add',
    'button_clear_filters' => 'Clear Filters',
    'list_of_local_dns_records' => 'List of local DNS records',
    'table_header_id' => 'ID',
    'table_header_empty1' => '',
    'table_header_time' => 'Time',
    'table_header_type' => 'Type',
    'table_header_message' => 'Message',
    'table_header_data1' => 'Data1',
    'table_header_data2' => 'Data2',
    'table_header_data3' => 'Data3',
    'table_header_data4' => 'Data4',
    'table_header_data5' => 'Data5',
    'table_header_action' => 'Action',
    'diagnosis_title' => 'Pi-hole diagnosis',
    'diagnosis_subtitle' => 'On this page, you can see messages from your Pi-hole concerning possible issues.',
    'add_new_dns_record' => 'Add a new domain/IP combination',
    'label_domain' => 'Domain:',
    'label_ip_address' => 'IP Address:',
    'placeholder_domain_list' => 'Domain or comma-separated list of domains',
    'placeholder_ip_address' => 'Associated IP address',
    'note' => 'Note:',
    'note_dns_records_order' => 'The order of locally defined DNS records is:',
    'note_dns_records_item1' => "The device's host name and <code>pi.hole</code>",
    'note_dns_records_item2' => 'Configured in a config file in <code>/etc/dnsmasq.d/</code>',
    'note_dns_records_item3' => 'Read from <code>/etc/hosts</code>',
    'note_dns_records_item4' => 'Read from the "Local (custom) DNS" list (stored in <code>/etc/pihole/custom.list</code>)',
    'note_only_first_record' => 'Only the first record will trigger an address-to-name association.',
    'button_add' => 'Add',
    'button_clear_filters' => 'Clear Filters',
    'list_of_local_dns_records' => 'List of local DNS records',
    'table_header_id' => 'ID',
    'table_header_empty1' => '',
    'table_header_time' => 'Time',
    'table_header_type' => 'Type',
    'table_header_message' => 'Message',
    'table_header_data1' => 'Data1',
    'table_header_data2' => 'Data2',
    'table_header_data3' => 'Data3',
    'table_header_data4' => 'Data4',
    'table_header_data5' => 'Data5',
    'table_header_action' => 'Action',
    'note_generate_debug_log' => 'If errors are shown, you can <a href="debug.php">generate a debug log</a>, which will do a thorough Pi-hole evaluation.',
    'button_add' => 'Add',
    'button_clear_filters' => 'Clear Filters',
    'adlist_group_management' => 'Adlist group management',
    'add_new_adlist' => 'Add a new adlist',
    'address' => 'Address:',
    'url_or_space_separated_urls' => 'URL or space-separated URLs',
    'comment' => 'Comment:',
    'adlist_description_optional' => 'Adlist description (optional)',
    'hints' => 'Hints:',
    'hint1' => 'Please run <code>pihole -g</code> or update your gravity list <a href="gravity.php">online</a> after modifying your adlists.',
    'hint2' => 'Multiple adlists can be added by separating each <i>unique</i> URL with a space',
    'hint3' => 'Click on the icon in the first column to get additional information about your lists. The icons correspond to the health of the list.',
    'add' => 'Add',
    'list_of_adlists' => 'List of adlists',
    'id' => 'ID',
    'address_table' => 'Address',
    'status' => 'Status',
    'comment_table' => 'Comment',
    'group_assignment' => 'Group assignment',
    'reset_sorting' => 'Reset sorting',
    'update_gravity_title' => 'Update Gravity (list of blocked domains)',
    'updating_message' => 'Updating... this may take a while. <strong>Please do not navigate away from or close this page.</strong>',
    'success_message' => 'Success!',
    'update_button' => 'Update',
    'adlist_group_management' => 'Adlist group management',
    'add_new_adlist' => 'Add a new adlist',
    'address' => 'Address:',
    'url_or_space_separated_urls' => 'URL or space-separated URLs',
    'comment' => 'Comment:',
    'adlist_description_optional' => 'Adlist description (optional)',
    'hints' => 'Hints:',
    'hint1' => 'Please run <code>pihole -g</code> or update your gravity list <a href="gravity.php">online</a> after modifying your adlists.',
    'hint2' => 'Multiple adlists can be added by separating each <i>unique</i> URL with a space',
    'hint3' => 'Click on the icon in the first column to get additional information about your lists. The icons correspond to the health of the list.',
    'add' => 'Add',
    'list_of_adlists' => 'List of adlists',
    'id' => 'ID',
    'address_table' => 'Address',
    'status' => 'Status',
    'comment_table' => 'Comment',
    'group_assignment' => 'Group assignment',
    'reset_sorting' => 'Reset sorting',

    // الترجمات الخاصة بتحديث الجاذبية
    'update_gravity_title' => 'Update Gravity (list of blocked domains)',
    'updating_message' => 'Updating... this may take a while. <strong>Please do not navigate away from or close this page.</strong>',
    'success_message' => 'Success!',
    'update_button' => 'Update',

    // الترجمات الخاصة بالبحث عن نطاقات محظورة
    'find_blocked_domain_title' => 'Find Blocked Domain In Lists',
    'domain_search_placeholder' => 'Domain to look for (example.com or sub.example.com)',
    'search_partial_match' => 'Search partial match',
    'search_exact_match' => 'Search exact match',
    'show_unlimited_results' => 'Show unlimited results.',
    'slow_if_many_domains' => 'This can be very slow if too many domains are returned.',
    'use_with_caution' => 'Use with caution.',
    'adlist_group_management' => 'Adlist group management',
    'add_new_adlist' => 'Add a new adlist',
    'address' => 'Address:',
    'url_or_space_separated_urls' => 'URL or space-separated URLs',
    'comment' => 'Comment:',
    'adlist_description_optional' => 'Adlist description (optional)',
    'hints' => 'Hints:',
    'hint1' => 'Please run <code>pihole -g</code> or update your gravity list <a href="gravity.php">online</a> after modifying your adlists.',
    'hint2' => 'Multiple adlists can be added by separating each <i>unique</i> URL with a space',
    'hint3' => 'Click on the icon in the first column to get additional information about your lists. The icons correspond to the health of the list.',
    'add' => 'Add',
    'list_of_adlists' => 'List of adlists',
    'id' => 'ID',
    'address_table' => 'Address',
    'status' => 'Status',
    'comment_table' => 'Comment',
    'group_assignment' => 'Group assignment',
    'reset_sorting' => 'Reset sorting',

    // الترجمات الخاصة بتحديث الجاذبية
    'update_gravity_title' => 'Update Gravity (list of blocked domains)',
    'updating_message' => 'Updating... this may take a while. <strong>Please do not navigate away from or close this page.</strong>',
    'success_message' => 'Success!',
    'update_button' => 'Update',

    // الترجمات الخاصة بالبحث عن نطاقات محظورة
    'find_blocked_domain_title' => 'Find Blocked Domain In Lists',
    'domain_search_placeholder' => 'Domain to look for (example.com or sub.example.com)',
    'search_partial_match' => 'Search partial match',
    'search_exact_match' => 'Search exact match',
    'show_unlimited_results' => 'Show unlimited results.',
    'slow_if_many_domains' => 'This can be very slow if too many domains are returned.',
    'use_with_caution' => 'Use with caution.',

    // الترجمات الخاصة بسجل التدقيق
    'audit_log_title' => 'Audit log (showing live data)',
    'allowed_queries' => 'Allowed queries',
    'blocked_queries' => 'Blocked queries',
    'domain' => 'Domain',
    'hits' => 'Hits',
    'actions' => 'Actions',
    'adlist_group_management' => 'Adlist group management',
    'add_new_adlist' => 'Add a new adlist',
    'address' => 'Address:',
    'url_or_space_separated_urls' => 'URL or space-separated URLs',
    'comment' => 'Comment:',
    'adlist_description_optional' => 'Adlist description (optional)',
    'hints' => 'Hints:',
    'hint1' => 'Please run <code>pihole -g</code> or update your gravity list <a href="gravity.php">online</a> after modifying your adlists.',
    'hint2' => 'Multiple adlists can be added by separating each <i>unique</i> URL with a space',
    'hint3' => 'Click on the icon in the first column to get additional information about your lists. The icons correspond to the health of the list.',
    'add' => 'Add',
    'list_of_adlists' => 'List of adlists',
    'id' => 'ID',
    'address_table' => 'Address',
    'status' => 'Status',
    'comment_table' => 'Comment',
    'group_assignment' => 'Group assignment',
    'reset_sorting' => 'Reset sorting',

    // الترجمات الخاصة بتحديث الجاذبية
    'update_gravity_title' => 'Update Gravity (list of blocked domains)',
    'updating_message' => 'Updating... this may take a while. <strong>Please do not navigate away from or close this page.</strong>',
    'success_message' => 'Success!',
    'update_button' => 'Update',

    // الترجمات الخاصة بالبحث عن نطاقات محظورة
    'find_blocked_domain_title' => 'Find Blocked Domain In Lists',
    'domain_search_placeholder' => 'Domain to look for (example.com or sub.example.com)',
    'search_partial_match' => 'Search partial match',
    'search_exact_match' => 'Search exact match',
    'show_unlimited_results' => 'Show unlimited results.',
    'slow_if_many_domains' => 'This can be very slow if too many domains are returned.',
    'use_with_caution' => 'Use with caution.',

    // الترجمات الخاصة بسجل التدقيق
    'audit_log_title' => 'Audit log (showing live data)',
    'allowed_queries' => 'Allowed queries',
    'blocked_queries' => 'Blocked queries',
    'domain' => 'Domain',
    'hits' => 'Hits',
    'actions' => 'Actions',

    // الترجمات الخاصة بتلك الصفحة الجديدة
    'not_authorized' => 'Not authorized',
    'failed_open_log' => 'Failed to open log file. Check permissions!\n',
    'output_last_lines_title' => 'Output the last lines of the pihole.log file (live)',
    'automatic_scrolling_on_update' => 'Automatic scrolling on update',
    'output_last_lines_ftl_title' => 'Output the last lines of the FTL.log file (live)',
    'automatic_scrolling_on_update' => 'Automatic scrolling on update',
    'generate_debug_log_title' => 'Generate debug log',
    'options' => 'Options:',
    'execute_database_integrity_check' => 'Execute database integrity check.',
    'database_integrity_check_warning' => 'This can add several minutes to debug log time.',
    'upload_debug_log_and_provide_debug_token' => 'Upload debug log and provide Debug Token.',
    'url_token_information' => 'The URL token will be shown at the end of the report, once finished.',
    'debug_log_generation_info' => 'Once you click this button a debug log will be generated and can automatically be uploaded if we detect a working internet connection.',
    'generate_debug_log_button' => 'Generate debug log',
    'network_overview_title' => 'Network overview',
    'download_csv_button' => 'Download CSV',
    
    // ترجمات رؤوس الجدول
    'table_id' => 'ID',
    'table_ip_address' => 'IP address',
    'table_hardware_address' => 'Hardware address',
    'table_interface' => 'Interface',
    'table_hostname' => 'Hostname',
    'table_first_seen' => 'First seen',
    'table_last_query' => 'Last Query',
    'table_number_of_queries' => 'Number of queries',
    'table_uses_pihole' => 'Uses Pi-hole',
    'table_action' => 'Action',
    
    // ترجمات توضيحات ألوان الخلفية
    'background_color_label' => 'Background color: Last query from this device seen ...',
    'background_color_just_now' => 'just now',
    'background_color_to' => '... to ...',
    'background_color_24_hours_ago' => '24 hours ago',
    'background_color_more_than_24_hours_ago' => '> 24 hours ago',
    'background_color_device_not_using_pihole' => 'Device does not use Pi-hole',
    'system' => 'System',
    'dns' => 'DNS',
    'dhcp' => 'DHCP',
    'web_interface' => 'Web interface',
    'api' => 'API',
    'privacy' => 'Privacy',
    'teleporter' => 'Teleporter',
    'ftl_information' => 'FTL Information',
    'ftl_version' => 'FTL version:',
    'pid' => 'Process identifier (PID):',
    'ftl_started' => 'Time FTL started:',
    'user_group' => 'User / Group:',
    'cpu_utilization' => 'Total CPU utilization:',
    'memory_utilization' => 'Memory utilization:',
    'used_memory' => 'Used memory:',
    'dns_cache_size' => 'DNS cache size:',
    'dns_cache_insertions' => 'DNS cache insertions:',
    'dns_cache_evictions' => 'DNS cache evictions:',
    'ftl_offline' => 'The FTL service is offline!',
    'dns_cache_documentation' => 'DNS cache documentation',
    'see_dns_cache_documentation' => 'See also our <a href="https://docs.pi-hole.net/ftldns/dns-cache/" rel="noopener" target="_blank">DNS cache documentation</a>.',
    'active' => 'Active',
    
];

$languages['system'] = 'System';
$languages['dns'] = 'DNS';
$languages['dhcp'] = 'DHCP';
$languages['web_interface'] = 'Web interface';
$languages['api'] = 'API';
$languages['privacy'] = 'Privacy';
$languages['teleporter'] = 'Teleporter';
$languages['ftl_information'] = 'FTL Information';
$languages['ftl_version'] = 'FTL version:';
$languages['pid'] = 'Process identifier (PID):';
$languages['ftl_started'] = 'Time FTL started:';
$languages['user_group'] = 'User / Group:';
$languages['cpu_utilization'] = 'Total CPU utilization:';
$languages['memory_utilization'] = 'Memory utilization:';
$languages['used_memory'] = 'Used memory:';
$languages['used_memory_title'] = 'Resident memory is the portion of memory occupied by a process that is held in main memory (RAM). The rest of the occupied memory exists in the swap space or file system.';
$languages['dns_cache_size'] = 'DNS cache size:';
$languages['dns_cache_size_title'] = 'Size of the DNS domain cache';
$languages['dns_cache_insertions'] = 'DNS cache insertions:';
$languages['dns_cache_insertions_title'] = 'Number of cache insertions';
$languages['dns_cache_evictions'] = 'DNS cache evictions:';
$languages['dns_cache_evictions_title'] = 'Number of cache entries that had to be removed although they are not expired (increase cache size to reduce this number)';
$languages['ftl_offline'] = 'The FTL service is offline!';
$languages['disable_query_logging'] = 'Disable query logging';
$languages['enable_query_logging'] = 'Enable query logging';
$languages['flush_network_table'] = 'Flush network table';
$languages['restart_dns_resolver'] = 'Restart DNS resolver';
$languages['flush_logs_last_24_hours'] = 'Flush logs (last 24 hours)';
$languages['power_off_system'] = 'Power off system';
$languages['restart_system'] = 'Restart system';
$languages['dhcp_settings'] = 'DHCP Settings';
$languages['dhcp_server_enabled'] = 'DHCP server enabled';
$languages['disable_router_dhcp_notice'] = "Make sure your router's DHCP server is disabled when using the Pi-hole DHCP server!";
$languages['ip_range'] = 'Range of IP addresses to hand out';
$languages['from'] = 'From';
$languages['to'] = 'To';
$languages['router_ip'] = 'Router (gateway) IP address';
$languages['piholedomain'] = 'Pi-hole domain name';
$languages['domain'] = 'Domain';
$languages['dhcp_leasetime'] = 'DHCP lease time';
$languages['lease_time_hours'] = 'Lease time in hours';
$languages['lease_time_hint'] = 'Hint: 0 = infinite, 24 = one day, 168 = one week, 744 = one month, 8760 = one year';
$languages['enable_dhcpv4_rapid_commit'] = 'Enable DHCPv4 rapid commit (fast address assignment)';
$languages['enable_ipv6_support'] = 'Enable IPv6 support (SLAAC + RA)';
$languages['active_dhcp_leases'] = 'Currently active DHCP leases';
$languages['mac_address'] = 'MAC address';
$languages['ip_address'] = 'IP address';
$languages['hostname'] = 'Hostname';
$languages['static_dhcp_leases'] = 'Static DHCP leases configuration';
$languages['add_static_lease'] = 'Add Static Lease';
$languages['save'] = 'Save';
$languages['currently_active_leases'] = 'Currently active DHCP leases';
$languages['static_leases'] = 'Static DHCP leases configuration';
$languages['add_mac'] = 'Add MAC';
$languages['add_ip'] = 'Add IP';
$languages['add_hostname'] = 'Add Hostname';
$languages['remove_static_lease'] = 'Remove Static Lease';
$languages['upstream_dns_servers'] = 'Upstream DNS Servers';
$languages['ipv4'] = 'IPv4';
$languages['ipv6'] = 'IPv6';
$languages['name'] = 'Name';
$languages['ecs_description'] = 'ECS (Extended Client Subnet) defines a mechanism for recursive resolvers to send partial client IP address information to authoritative DNS name servers. Content Delivery Networks (CDNs) and latency-sensitive services use this to give geo-located responses when responding to name lookups coming through public DNS resolvers. <em>Note that ECS may result in reduced privacy.</em>';
$languages['custom_1_ipv4'] = 'Custom 1 (IPv4)';
$languages['custom_2_ipv4'] = 'Custom 2 (IPv4)';
$languages['custom_3_ipv6'] = 'Custom 3 (IPv6)';
$languages['custom_4_ipv6'] = 'Custom 4 (IPv6)';
$languages['interface_settings'] = 'Interface settings';
$languages['recommended_setting'] = 'Recommended setting';
$languages['allow_only_local_requests'] = 'Allow only local requests';
$languages['allow_only_local_requests_desc'] = 'Allows only queries from devices that are at most one hop away (local devices)';
$languages['potentially_dangerous_options'] = 'Potentially dangerous options';
$languages['respond_only_on_interface'] = 'Respond only on interface %s';
$languages['bind_only_to_interface'] = 'Bind only to interface %s';
$languages['permit_all_origins'] = 'Permit all origins';
$languages['dangerous_options_desc'] = 'These options are dangerous on devices directly connected to the Internet such as cloud instances and are only safe if your Pi-hole is properly firewalled. In a typical at-home setup where your Pi-hole is located within your local network (and you have <strong>not</strong> forwarded port 53 in your router!) they are safe to use.';
$languages['advanced_dns_settings'] = 'Advanced DNS settings';
$languages['never_forward_non_fqdn_queries'] = 'Never forward non-FQDN <code>A</code> and <code>AAAA</code> queries';
$languages['never_forward_non_fqdn_queries_desc'] = 'When there is a Pi-hole domain set and this box is ticked, this asks FTL that this domain is purely local and FTL may answer queries from <code>/etc/hosts</code> or DHCP leases but should never forward queries on that domain to any upstream servers. If Conditional Forwarding is enabled, unticking this box may cause a partial DNS loop under certain circumstances (e.g. if a client would send TLD DNSSEC queries).';
$languages['never_forward_reverse_lookups'] = 'Never forward reverse lookups for private IP ranges';
$languages['never_forward_reverse_lookups_desc'] = 'All reverse lookups for private IP ranges (i.e., <code>192.168.0.x/24</code>, etc.) which are not found in <code>/etc/hosts</code> or the DHCP leases are answered with "no such domain" rather than being forwarded upstream. The set of prefixes affected is the list given in <a href="https://tools.ietf.org/html/rfc6303">RFC6303</a>.<br><strong>Important</strong>: Enabling these two options may increase your privacy, but may also prevent you from being able to access local hostnames if the Pi-hole is not used as DHCP server.';
$languages['use_dnssec'] = 'Use DNSSEC';
$languages['use_dnssec_desc'] = 'Validate DNS replies and cache DNSSEC data. When forwarding DNS queries, Pi-hole requests the DNSSEC records needed to validate the replies. If a domain fails validation or the upstream does not support DNSSEC, this setting can cause issues resolving domains. Use an upstream DNS server which supports DNSSEC when activating DNSSEC. Note that the size of your log might increase significantly when enabling DNSSEC. A DNSSEC resolver test can be found <a href="https://wander.science/projects/dns/dnssec-resolver-test/" rel="noopener" target="_blank">here</a>.';
$languages['rate_limiting'] = 'Rate-limiting';
$languages['rate_limiting_desc'] = 'Block clients making more than <input type="number" name="rate_limit_count" value="%s" min="0" step="10" style="width: 5em;"> queries within <input type="number" name="rate_limit_interval" value="%s" min="0" step="10" style="width: 4em;"> seconds.<br>When a client makes too many queries in too short time, it gets rate-limited. Rate-limited queries are answered with a <code>REFUSED</code> reply and not further processed by FTL and prevent Pi-holes getting overwhelmed by rogue clients. It is important to note that rate-limiting is happening on a per-client basis. Other clients can continue to use FTL while rate-limited clients are short-circuited at the same time.<br>Rate-limiting may be disabled altogether by setting both values to zero. See <a href="https://docs.pi-hole.net/ftldns/configfile/#rate_limit" target="_blank">our documentation</a> for further details.';
$languages['conditional_forwarding'] = 'Conditional forwarding';
$languages['conditional_forwarding_desc'] = 'If not configured as your DHCP server, Pi-hole typically won\'t be able to determine the names of devices on your local network. As a result, tables such as Top Clients will only show IP addresses.<br>One solution for this is to configure Pi-hole to forward these requests to your DHCP server (most likely your router), but only for devices on your home network. To configure this we will need to know the IP address of your DHCP server and which addresses belong to your local network. Exemplary input is given below as placeholder in the text boxes (if empty).<br>If your local network spans 192.168.0.1 - 192.168.0.255, then you will have to input <code>192.168.0.0/24</code>. If your local network is 192.168.47.1 - 192.168.47.255, it will be <code>192.168.47.0/24</code> and similar. If your network is larger, the CIDR has to be different, for instance a range of 10.8.0.1 - 10.8.255.255 results in <code>10.8.0.0/16</code>, whereas an even wider network of 10.0.0.1 - 10.255.255.255 results in <code>10.0.0.0/8</code>. Setting up IPv6 ranges is exactly similar to setting up IPv4 here and fully supported. Feel free to reach out to us on our <a href="https://discourse.pi-hole.net" rel="noopener" target="_blank">Discourse forum</a> in case you need any assistance setting up local host name resolution for your particular system.<br>You can also specify a local domain name (like <code>fritz.box</code>) to ensure queries to devices ending in your local domain name will not leave your network, however, this is optional. The local domain name must match the domain name specified in your DHCP server for this to work. You can likely find it within the DHCP settings.<br>Enabling Conditional Forwarding will also forward all hostnames (i.e., non-FQDNs) to the router when "Never forward non-FQDNs" is <em>not</em> enabled.';
$languages['use_conditional_forwarding'] = 'Use Conditional Forwarding';
$languages['local_network_cidr'] = 'Local network in <a href="https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing" target="_blank">CIDR notation</a>';
$languages['dhcp_server_ip'] = 'IP address of your DHCP server (router)';
$languages['local_domain_optional'] = 'Local domain name (optional)';
$languages['specify_mac_mandatory'] = 'Specifying the MAC address is mandatory and only one entry per MAC address is allowed. If the IP address is omitted and a host name is given, the IP address will still be generated dynamically and the specified host name will be used. If the host name is omitted, only a static lease will be added.';
$languages['interface_settings'] = 'Interface settings';
$languages['recommended_setting'] = 'Recommended setting';
$languages['allow_only_local_requests'] = 'Allow only local requests';
$languages['allow_only_local_requests_desc'] = 'Allows only queries from devices that are at most one hop away (local devices)';
$languages['potentially_dangerous_options'] = 'Potentially dangerous options';
$languages['make_sure_firewalled'] = 'Make sure your Pi-hole is properly firewalled!';
$languages['respond_only_on_interface'] = 'Respond only on interface %s';
$languages['bind_only_to_interface'] = 'Bind only to interface %s';
$languages['permit_all_origins'] = 'Permit all origins';
$languages['dangerous_options_desc'] = 'These options are dangerous on devices directly connected to the Internet such as cloud instances and are only safe if your Pi-hole is properly firewalled. In a typical at-home setup where your Pi-hole is located within your local network (and you have <strong>not</strong> forwarded port 53 in your router!) they are safe to use.';
$languages['see_documentation'] = 'See <a href="https://docs.pi-hole.net/ftldns/interfaces/" target="_blank">our documentation</a> for further technical details.';

// إزالة المفاتيح أو القيم المكررة
$languages = $languages;
// $languages = array_unique($result);